name: Deploy Vue App

on:
  push:
    branches: [ main ]
    paths:
      - '**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /tmp/frontend-deploy
            rm -rf /tmp/frontend-deploy/*


      - name: Move files and set permissions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo rm -rf /var/www/frontend/*
            sudo cp -r /tmp/frontend-deploy/* /var/www/frontend/
            sudo chown -R www-data:www-data /var/www/frontend
            sudo chmod -R 755 /var/www/frontend